name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call Render Deploy Hook
        uses: tyrrrz/action-http-request@master
        with:
          url: ${{ secrets.RENDER_DEPLOY_HOOK }}